2020-12-20 17:19:08,628 ERROR: Exception on /reset_password_request [POST] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 157, in reset_password_request
    send_password_reset_email(user)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/email.py", line 18, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/models.py", line 53, in get_reset_password_token
    {'reset_password':self.id, 'exp':time() + expires_in}, app.config['SECRET_KEY'],algorithm=['HS256'].decode('utf-8')
AttributeError: 'list' object has no attribute 'decode'
2020-12-20 17:20:41,814 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 17:20:50,690 ERROR: Exception on /reset_password_request [POST] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 157, in reset_password_request
    send_password_reset_email(user)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/email.py", line 18, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/models.py", line 53, in get_reset_password_token
    {'reset_password':self.id, 'exp':time() + expires_in}, app.config['SECRET_KEY'],algorithm=['HS256']).decode('utf-8')
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jwt/api_jwt.py", line 65, in encode
    json_payload, key, algorithm, headers, json_encoder
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jwt/api_jws.py", line 88, in encode
    if algorithm not in self._valid_algs:
TypeError: unhashable type: 'list'
2020-12-20 17:35:05,326 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 17:35:12,624 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 18:02:48,528 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:42]
2020-12-20 18:05:00,702 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:42]
2020-12-20 18:09:36,050 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:42]
2020-12-20 18:17:26,339 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:42]
2020-12-20 18:17:44,097 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:42]
2020-12-20 18:33:50,275 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:44]
2020-12-20 19:12:24,076 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:46]
2020-12-20 19:14:50,125 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:46]
2020-12-20 19:19:01,927 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:46]
