2020-12-19 21:52:42,470 ERROR: Exception on /explore [GET] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 145, in explore
    return render_template('index.html',title='Explore',posts=posts.items, next_url=next_url, prev_url = prev_url)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/index.html", line 28, in template
    {% endblock %}
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2020-12-19 21:53:26,687 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:38]
2020-12-19 22:20:22,014 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 02:28:09,635 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 02:28:16,218 ERROR: Exception on /login [GET] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 42, in login
    return render_template('login.html',title='Sign In',form=form)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/base.html", line 36, in top-level template code
    {% block content %}{% endblock %}
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/templates/login.html", line 27, in block "content"
    <a href="{{ url_for('reset_password_request') }}">Click ti Reset It</a>
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'edit_profile' instead?
2020-12-20 17:16:36,580 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
2020-12-20 17:17:44,124 ERROR: Exception on /reset_password_request [POST] [in /home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/routes.py", line 157, in reset_password_request
    send_password_reset_email(user)
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/email.py", line 18, in send_password_reset_email
    token = user.get_reset_password_token()
  File "/home/akshay/Documents/flask-projects/microblog/micro-venv/app/models.py", line 53, in get_reset_password_token
    {'reset_password':self.id, 'exp':time() + expires_in}, app.config['SEXRET_KEY'],algorithm=['HS256'].decode('utf-8')
KeyError: 'SEXRET_KEY'
2020-12-20 17:19:00,501 INFO: Microblog startup [in /home/akshay/Documents/flask-projects/microblog/micro-venv/app/__init__.py:40]
